### PR TITLE
Fix issue where #[cfg(...)] are not propogated to emitted debug implementation. 

### LINKED ISSUE #19: Debug macro generation does not observe #cfg(feature) gates correctly
See https://github.com/microsoft/igvm/issues/63, but essentially if you have an enum variant with a given feature cfg gate, it doesn't make it to the emitted debug impl which leaves it broken if not built with that feature. I'll take a look at fixing this. 

```rust
// Recursive expansion of open_enum macro
// =======================================

#[allow(clippy::exhaustive_structs)]
#[doc = " Enum describing different isolation platforms for"]
#[doc = " [`IGVM_VHS_SUPPORTED_PLATFORM`] structures."]
#[doc = " cbindgen:prefix-with-name=true"]
#[doc = " cbindgen:rename-all=ScreamingSnakeCase"]
#[repr(transparent)]
#[derive(
    ::core::cmp::PartialEq, ::core::cmp::Eq, AsBytes, FromBytes, FromZeroes, Clone, Copy, Hash,
)]
pub struct IgvmPlatformType(pub u8);

#[allow(non_upper_case_globals)]
impl IgvmPlatformType {
    #[doc = " Native platform type without isolation."]
    pub const NATIVE: IgvmPlatformType = IgvmPlatformType(0);
    #[doc = " Platform type of Hyper-V\'s which supports VSM isolation."]
    pub const VSM_ISOLATION: IgvmPlatformType = IgvmPlatformType(1);
    #[doc = " AMD SEV-SNP."]
    pub const SEV_SNP: IgvmPlatformType = IgvmPlatformType(2);
    #[doc = " Intel TDX."]
    pub const TDX: IgvmPlatformType = IgvmPlatformType(3);
    #[doc = " AMD SEV."]
    #[cfg(feature = "unstable")]
    #[cfg_attr(docsrs, doc(cfg(feature = "unstable")))]
    pub const SEV: IgvmPlatformType = IgvmPlatformType(4);
    #[doc = " AMD SEV-ES"]
    #[cfg(feature = "unstable")]
    #[cfg_attr(docsrs, doc(cfg(feature = "unstable")))]
    pub const SEV_ES: IgvmPlatformType = IgvmPlatformType(5);
}
impl ::core::fmt::Debug for IgvmPlatformType {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        #![allow(unreachable_patterns)]
        let s = match *self {
            Self::NATIVE => "NATIVE",
            Self::VSM_ISOLATION => "VSM_ISOLATION",
            Self::SEV_SNP => "SEV_SNP",
            Self::TDX => "TDX",
            Self::SEV => "SEV",
            Self::SEV_ES => "SEV_ES",
            _ => {
                return fmt.debug_tuple("IgvmPlatformType").field(&self.0).finish();
            }
        };
        fmt.pad(s)
    }
}
```

### PR DESCRIPTION
**Pull request by chris-oo**
When using feature gates with debug derives, the generated debug implementation does not correctly cfg gate enums that should be cfg gated, resulting in code that does not compile with the given feature. 

Fix this by making sure we emit `[#cfg(...)]` to the generated debug variants so that the code is correctly feature gated. 

Fixes #19

### CODE REVIEW

**Comment by chris-oo** [comment]
I'm not an expert on proc macros, so if you have anything you'd like to see different, much appreciated!

**Comment by chris-oo** [comment]
Bump? @kupiakos I was hoping to get this soon, as there's some other changes that I'd like to merge in the igvm crate that needs this.

File: tests/derives.rs [hunk 1]
```diff
@@ -25,6 +25,17 @@ pub enum Color {
...
 }
 
+#[open_enum]
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+#[repr(u32)]
+pub enum ColorWithFeatures {
+    Red = 1,
+    Blue = 2,
+    /// Test doc
+    #[cfg(feature = "orange")]
```
Comment (kupiakos) [inline tests/derives.rs:35]: D'you have any ideas for testing that this works correctly with the `cfg` enabled?

**Comment by kupiakos** [comment]
Sorry for the delay! Published in [v0.5.2](https://crates.io/crates/open-enum/0.5.2).

**Comment by chris-oo** [comment]
Thanks, no problem appreciate it!

File: tests/derives.rs (hunk 1 above)
Comment (chris-oo) [reply tests/derives.rs:35]: Hmm... we could maybe have a test enabled feature and have an enumeration with cfg enabled on it? Perhaps I should have done that in the PR. 

FWIW in the igvm repo we're testing both, but I can see about submitting a follow up PR to do the same here.
